# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('open', 'Open'), ('partial', 'Partial'), ('complete', 'Complete'), ('cancelled', 'Cancelled')], max_length=15),
        ),
    ]
