# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleight', '0002_auto_20160821_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nonce',
            field=models.BigIntegerField(),
        ),
    ]
