# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleight', '0003_auto_20160821_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='amount',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=20),
        ),
    ]
